import os
import json
import glob
import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

st.set_page_config(
    page_title="Audio Temporal Reasoning Pipeline",
    page_icon="🎧",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Helpers ───────────────────────────────────────────────────────────────────

def load_json(path):
    if not os.path.exists(path):
        return None
    with open(path, encoding="utf-8") as f:
        return json.load(f)

def load_yaml(path):
    if not os.path.exists(path):
        return None
    import yaml
    with open(path, encoding="utf-8") as f:
        return yaml.safe_load(f)

COLORS = {
    "base":   "#B5D4F4",
    "sft":    "#378ADD",
    "green":  "#1D9E75",
    "red":    "#D85A30",
    "purple": "#7F77DD",
    "orange": "#FFA500",
}

# ── Load all outputs ──────────────────────────────────────────────────────────

report      = load_json("outputs/benchmark_report.json")
predictions = load_json("outputs/predictions.json")
train_data  = load_json("data/train.json")
test_data   = load_json("data/test.json")
pref_data   = load_json("data/preference_pairs.json")
ft_config   = load_yaml("configs/finetune_config.yaml")
dpo_config  = load_yaml("configs/dpo_config.yaml")

# ── Sidebar ───────────────────────────────────────────────────────────────────

with st.sidebar:
    st.title("Pipeline")
    st.markdown("**Qwen2.5-Omni-7B** — QLoRA SFT")
    st.caption("DPO stage is experimental — see README")
    st.divider()

    st.markdown("**Navigation**")
    page = st.radio(
        "nav",
        ["Overview", "Dataset", "Training Config", "Evaluation", "Latency",
         "Predictions", "DPO Pairs"],
        label_visibility="collapsed",
    )
    st.divider()

    st.markdown("**Custom paths**")
    report_path = st.text_input("Report JSON", "outputs/benchmark_report.json")
    pred_path   = st.text_input("Predictions JSON", "outputs/predictions.json")
    if st.button("Reload", use_container_width=True):
        report      = load_json(report_path)
        predictions = load_json(pred_path)
        st.success("Reloaded")

    st.divider()
    st.caption("Audio Temporal Reasoning Pipeline\nBuilt by Mounish")

# ── Page header ───────────────────────────────────────────────────────────────

st.title("Audio Temporal Reasoning Pipeline")
st.markdown(
    "**Qwen2.5-Omni-7B + QLoRA** &nbsp;|&nbsp; "
    "Dataset: AudioCaps &nbsp;|&nbsp; "
    "Task: Audio hallucination reduction & temporal reasoning"
)

# Warn loudly when the loaded predictions are simulated (produced by
# scripts/make_fake_dashboard_data.py) rather than real model output.
if predictions and any(p.get("simulated") for p in predictions):
    st.error(
        "⚠️ **SIMULATED DATA** — these predictions were generated by "
        "`scripts/make_fake_dashboard_data.py`, not by a model. All metrics "
        "shown are meaningless. Run `scripts/run_batch_inference.py` on a "
        "GPU to produce real results."
    )

st.divider()

# =============================================================================
# PAGE: OVERVIEW
# =============================================================================

if page == "Overview":

    st.subheader("What this project does")
    st.markdown(
        "Fine-tunes **Qwen2.5-Omni-7B** — a multimodal model that hears audio "
        "and generates text — to describe the **temporal order of sound "
        "events** in real audio clips, reducing hallucination (describing "
        "sounds that aren't there, or getting their order wrong). "
        "Trained with QLoRA on AudioCaps. See [KAGGLE_GUIDE.md](.) for the "
        "free training recipe."
    )

    st.divider()
    st.subheader("Benchmark results")

    if report:
        r1c1, r1c2, r1c3, r1c4 = st.columns(4)
        r2c1, r2c2, r2c3 = st.columns(3)

        with r1c1:
            st.metric("Hallucination Rate", f"{report.get('hallucination_rate','N/A')}%")
        with r1c2:
            st.metric("ROUGE-1", f"{report.get('rouge_1','N/A')}%")
        with r1c3:
            st.metric("ROUGE-L", f"{report.get('rouge_l','N/A')}%")
        with r1c4:
            st.metric("BERTScore F1", f"{report.get('bert_score','N/A')}%")
        with r2c1:
            st.metric("Temporal Ordering Acc.", f"{report.get('temporal_ordering_accuracy','N/A')}%")
        with r2c2:
            st.metric("Sound Event Recall", f"{report.get('sound_event_recall','N/A')}%")
        with r2c3:
            st.metric("Latency p95", f"{report.get('latency_p95_ms','N/A')} ms")
    else:
        st.info(
            "No benchmark report yet. Run `scripts/run_batch_inference.py` "
            "(base and fine-tuned) to produce `outputs/benchmark_report.json`, "
            "then reload this page. See KAGGLE_GUIDE.md."
        )

# =============================================================================
# PAGE: DATASET
# =============================================================================

elif page == "Dataset":

    st.subheader("AudioCaps Dataset")

    d1, d2, d3 = st.columns(3)
    with d1:
        st.metric("Train samples", len(train_data) if train_data else 0)
    with d2:
        st.metric("Test samples",  len(test_data)  if test_data  else 0)
    with d3:
        st.metric("DPO pairs",     len(pref_data)  if pref_data  else 0)

    st.markdown(
        "**Source:** AudioCaps (real YouTube audio + human captions)  \n"
        "**Audio:** ~10-second clips, 16 kHz mono WAV  \n"
        "**Prompts:** temporal-reasoning question templates  \n"
        "**Leakage guard:** no YouTube ID in training may appear in test "
        "(enforced in `scripts/prepare_audiocaps.py`)"
    )

    if not train_data and not test_data:
        st.info(
            "No data yet. Run `python scripts/prepare_audiocaps.py` "
            "(or `prepare_audiocaps_hf.py` to stream from Hugging Face "
            "instead of YouTube)."
        )

    st.divider()

    if test_data:
        st.subheader("Prompt distribution (test set)")
        prompts = [s.get("prompt", "") for s in test_data]
        prompt_counts = pd.Series(prompts).value_counts().reset_index()
        prompt_counts.columns = ["Prompt", "Count"]
        fig_p = px.bar(
            prompt_counts, x="Count", y="Prompt", orientation="h",
            color="Count", color_continuous_scale="Blues",
            height=max(320, len(prompt_counts) * 36),
        )
        fig_p.update_layout(yaxis=dict(autorange="reversed"), showlegend=False,
                            coloraxis_showscale=False)
        st.plotly_chart(fig_p, use_container_width=True)
        st.divider()

    if train_data:
        st.subheader("Sample train records")
        st.dataframe(pd.DataFrame([
            {"Audio": s["audio"], "Prompt": s["prompt"], "Answer": s["answer"]}
            for s in train_data[:50]
        ]), use_container_width=True, hide_index=True)

    if test_data:
        st.subheader("Sample test records (AudioCaps captions)")
        st.dataframe(pd.DataFrame([
            {"Audio": s["audio"], "Prompt": s["prompt"], "Answer": s["answer"]}
            for s in test_data[:20]
        ]), use_container_width=True, hide_index=True)

# =============================================================================
# PAGE: TRAINING CONFIG
# =============================================================================

elif page == "Training Config":

    st.subheader("QLoRA training configuration")

    if ft_config:
        lora_r = ft_config["lora"]["r"]
        alpha  = ft_config["lora"]["lora_alpha"]
        lr_ft  = ft_config["training"]["learning_rate"]
        ep_ft  = ft_config["training"]["num_epochs"]
        ml_ft  = ft_config["training"]["max_length"]
        ga_ft  = ft_config["training"]["gradient_accumulation_steps"]

        summary_df = pd.DataFrame({
            "Setting":       ["LoRA rank (r)", "LoRA alpha", "Epochs",
                              "Learning rate", "Max length", "Grad accum"],
            "Value":         [lora_r, alpha, ep_ft, lr_ft, ml_ft, ga_ft],
        })
        st.dataframe(summary_df, use_container_width=True, hide_index=True)

        st.divider()
        st.subheader("finetune_config.yaml")
        st.json(ft_config)

        st.divider()
        st.subheader("LoRA target modules")
        modules = ft_config.get("lora", {}).get("target_modules", [])
        st.code("\n".join(modules), language="text")
    else:
        st.info("configs/finetune_config.yaml not found.")

    if dpo_config:
        st.divider()
        st.subheader("dpo_config.yaml (experimental — see README)")
        st.json(dpo_config)

# =============================================================================
# PAGE: EVALUATION
# =============================================================================

elif page == "Evaluation":

    st.subheader("Evaluation metrics")

    if report:
        metric_map = {
            "rouge_1":                    ("ROUGE-1",               COLORS["sft"]),
            "rouge_l":                    ("ROUGE-L",               COLORS["purple"]),
            "bert_score":                 ("BERTScore F1",          COLORS["orange"]),
            "temporal_ordering_accuracy": ("Temporal Ordering Acc.", COLORS["green"]),
            "sound_event_recall":         ("Sound Event Recall",    COLORS["base"]),
            "hallucination_rate":         ("Hallucination Rate",    COLORS["red"]),
        }
        names, values, colors = [], [], []
        for key, (label, color) in metric_map.items():
            if key in report:
                names.append(label)
                values.append(report[key])
                colors.append(color)

        if values:
            fig_bar = go.Figure(go.Bar(
                x=values, y=names, orientation="h",
                text=[f"{v:.1f}%" for v in values],
                textposition="outside",
                marker_color=colors,
            ))
            fig_bar.update_layout(
                xaxis=dict(range=[0, 112], title="Score (%)"),
                height=400, showlegend=False,
            )
            st.plotly_chart(fig_bar, use_container_width=True)

        st.divider()
        st.subheader("Full benchmark report")
        col_l, col_r = st.columns(2)
        items = list(report.items())
        mid   = len(items) // 2
        with col_l:
            for k, v in items[:mid]:
                st.write(f"**{k}** : `{v}`")
        with col_r:
            for k, v in items[mid:]:
                st.write(f"**{k}** : `{v}`")
    else:
        st.info(
            "No benchmark report found. Run `scripts/run_batch_inference.py` "
            "to produce `outputs/benchmark_report.json`."
        )

# =============================================================================
# PAGE: LATENCY
# =============================================================================

elif page == "Latency":

    st.subheader("Latency analysis")

    if report:
        lc1, lc2, lc3, lc4 = st.columns(4)
        lc1.metric("p50",  f"{report.get('latency_p50_ms','N/A')} ms")
        lc2.metric("p95",  f"{report.get('latency_p95_ms','N/A')} ms")
        lc3.metric("Mean", f"{report.get('latency_mean_ms','N/A')} ms")
        lc4.metric("Max",  f"{report.get('latency_max_ms','N/A')} ms")
        st.divider()

    if predictions:
        latencies = [s["latency_ms"] for s in predictions if s.get("latency_ms", -1) > 0]
        if latencies:
            col_h, col_c = st.columns(2)
            with col_h:
                fig_hist = px.histogram(
                    x=latencies, nbins=40,
                    labels={"x": "Latency (ms)"},
                    title=f"Latency distribution ({len(latencies)} samples)",
                    color_discrete_sequence=[COLORS["purple"]],
                )
                fig_hist.update_layout(height=340, bargap=0.05)
                st.plotly_chart(fig_hist, use_container_width=True)

            with col_c:
                sorted_lat = sorted(latencies)
                n = len(sorted_lat)
                fig_cdf = go.Figure()
                fig_cdf.add_trace(go.Scatter(
                    x=sorted_lat, y=[(i+1)/n*100 for i in range(n)],
                    mode="lines", line=dict(color=COLORS["green"], width=2.5), name="CDF",
                ))
                fig_cdf.add_hline(y=50, line_dash="dot", annotation_text="p50", line_color="#888")
                fig_cdf.add_hline(y=95, line_dash="dot", annotation_text="p95", line_color=COLORS["red"])
                fig_cdf.update_layout(
                    title="Cumulative latency (CDF)",
                    xaxis_title="Latency (ms)", yaxis_title="Percentile (%)", height=340,
                )
                st.plotly_chart(fig_cdf, use_container_width=True)

            st.divider()
            st.subheader("Per-sample latency")
            lat_df = pd.DataFrame([
                {"Sample": i+1, "Audio": s.get("audio",""), "Latency (ms)": s["latency_ms"]}
                for i, s in enumerate(predictions) if s.get("latency_ms",-1) > 0
            ])
            fig_line = px.line(lat_df, x="Sample", y="Latency (ms)",
                               title=f"Latency per sample ({len(lat_df)} total)",
                               color_discrete_sequence=[COLORS["purple"]])
            fig_line.update_layout(height=300)
            st.plotly_chart(fig_line, use_container_width=True)
    else:
        st.info("No predictions file found.")

# =============================================================================
# PAGE: PREDICTIONS
# =============================================================================

elif page == "Predictions":

    st.subheader("Model predictions explorer")

    if predictions:
        total   = len(predictions)
        skipped = sum(1 for s in predictions if s.get("model_prediction") == "AUDIO_NOT_FOUND")

        c1, c2, c3, c4 = st.columns(4)
        c1.metric("Total samples",     total)
        c2.metric("Evaluated",         total - skipped)
        c3.metric("Skipped",           skipped)
        c4.metric("Dataset",           "AudioCaps")

        st.divider()

        search = st.text_input("Search predictions or prompts", placeholder="e.g. dog, rain, thunder...")

        rows = []
        for s in predictions:
            pred   = s.get("model_prediction", "")
            prompt = s.get("prompt", "")
            answer = s.get("answer", "")
            if search and search.lower() not in pred.lower() and search.lower() not in prompt.lower() and search.lower() not in answer.lower():
                continue
            rows.append({
                "YouTube ID":   s.get("youtube_id", s.get("audio", "")),
                "Prompt":       prompt,
                "Prediction":   pred,
                "Ground Truth": answer,
                "Latency (ms)": s.get("latency_ms", -1),
            })

        if rows:
            st.dataframe(pd.DataFrame(rows), use_container_width=True, height=480)
            st.caption(f"Showing {len(rows)} of {total} samples")
        else:
            st.warning("No results match the search query.")

        st.divider()
        st.subheader("Side-by-side viewer")
        idx = st.slider("Sample index", 0, total - 1, 0)
        sample = predictions[idx]
        st.markdown(f"**Prompt:** *{sample.get('prompt','N/A')}*")
        st.markdown(f"**Audio:** `{sample.get('youtube_id', sample.get('audio','N/A'))}` at t={sample.get('start_time','?')}s  |  Latency: {sample.get('latency_ms','N/A')} ms")
        col_p, col_g = st.columns(2)
        with col_p:
            st.markdown("**Model Prediction**")
            st.info(sample.get("model_prediction", "N/A"))
        with col_g:
            st.markdown("**Ground Truth (AudioCaps caption)**")
            st.success(sample.get("answer", "N/A"))
    else:
        st.info("No predictions file found. Run `python scripts/run_batch_inference.py`.")

# =============================================================================
# PAGE: DPO PAIRS
# =============================================================================

elif page == "DPO Pairs":

    st.subheader("DPO preference pairs (experimental)")
    st.caption(
        "TRL's DPOTrainer here receives text only, not audio, so it can "
        "teach caption *style* preferences but not audio grounding. See README."
    )

    if pref_data:
        p1, p2 = st.columns(2)
        p1.metric("Total pairs", len(pref_data))
        p2.markdown(
            "**Strategy:** ground truth caption = `chosen`, "
            "caption from a different audio clip = `rejected`"
        )

        st.divider()

        chosen_lens   = [len(p["chosen"].split())   for p in pref_data]
        rejected_lens = [len(p["rejected"].split()) for p in pref_data]

        fig_len = go.Figure()
        fig_len.add_trace(go.Histogram(x=chosen_lens,   name="Chosen",   marker_color=COLORS["green"], opacity=0.75))
        fig_len.add_trace(go.Histogram(x=rejected_lens, name="Rejected", marker_color=COLORS["red"],   opacity=0.75))
        fig_len.update_layout(
            barmode="overlay",
            title="Response length distribution (words)",
            xaxis_title="Word count", yaxis_title="Count", height=300,
        )
        st.plotly_chart(fig_len, use_container_width=True)

        st.divider()
        st.subheader("Browse preference pairs")
        idx = st.slider("Pair index", 0, len(pref_data) - 1, 0)
        pair = pref_data[idx]
        st.markdown(f"**Prompt:** *{pair['prompt']}*")
        col_c, col_r = st.columns(2)
        with col_c:
            st.markdown("**Chosen — correct temporal description**")
            st.success(pair["chosen"])
        with col_r:
            st.markdown("**Rejected — mismatched / hallucinated**")
            st.error(pair["rejected"])

        st.divider()
        st.subheader("All pairs")
        st.dataframe(pd.DataFrame([{
            "Prompt":       p["prompt"][:60] + "...",
            "Chosen":       p["chosen"][:80] + "...",
            "Rejected":     p["rejected"][:80] + "...",
            "Chosen words": len(p["chosen"].split()),
            "Rejected words": len(p["rejected"].split()),
        } for p in pref_data]), use_container_width=True, height=400, hide_index=True)
    else:
        st.info("No preference pairs found. Run `python scripts/prepare_audiocaps.py`.")
